name: Lint and test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  lint-and-test:
    name: Lint and test the code
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .ssh directory exists even if it's empty
        run: mkdir -p /home/runner/.ssh

      - name: Run lint and test
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: >
            /bin/bash -c "
              go mod download &&
              task lint &&
              task test
            "
